### ISSUE TITLE
TODO: Implementing Vectorized Search

### ISSUE THREAD

**Issue by Advayp** [Advayp/spice-ai-assessment#12]
## Goal: Search through notes quickly for similarities to a given query 
Steps:
 - [x] Add embeddings to the Spicepod (picking any appropriate model)
 - [x] Create some helper functions for returning all matches for a particular query 
 - [x] Implement a route on the API that enables users to search the dataset with a particular query
